# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClLauncher < Formula
  desc "CLI launcher for Claude Code / Codex with provider profiles"
  homepage "https://github.com/unliu/cl-launcher"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/unliu/cl-launcher/releases/download/v0.1.0/cl-launcher_0.1.0_darwin_amd64.tar.gz"
      sha256 "d722ad5ff10cbe70d79f046a34c605ba604a2fa82fbbe3e41de795b93418c758"

      define_method(:install) do
        bin.install "cl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/unliu/cl-launcher/releases/download/v0.1.0/cl-launcher_0.1.0_darwin_arm64.tar.gz"
      sha256 "ded3fd959f15f9d3433ff6ae420a61ed2073ae714b094577460615eba694278a"

      define_method(:install) do
        bin.install "cl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/unliu/cl-launcher/releases/download/v0.1.0/cl-launcher_0.1.0_linux_amd64.tar.gz"
      sha256 "a80b3c1daffb3e18be18781035fd3cb6cec1c864a68e90ad75fe0b212ba428e5"
      define_method(:install) do
        bin.install "cl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/unliu/cl-launcher/releases/download/v0.1.0/cl-launcher_0.1.0_linux_arm64.tar.gz"
      sha256 "e098bd4dd2409f8110291b509de242f1f6eb712f24605d66f226d93e999802de"
      define_method(:install) do
        bin.install "cl"
      end
    end
  end
end
